### ISSUE TITLE
Regression: Users must exist before they can be added to roles

### ISSUE THREAD

**Issue by cjcolvar** [samvera/hydra-role-management#3]
The default role mapper allowed a username to be added to a role before a user has registered.  

We use this for people wanting access to our test server.  They email us requesting access, we add them to a role, and send them an email with instructions for how to create an account through IU's CAS.

Another use case would be students or TAs that you want added to a role before a term starts and not have to negotiate with each one to add them to a role after they have registered with the system.

The existing behavior could be easily restored by creating a user when they are added to a group and this works in our system which uses devise+omniauth but wouldn't with default devise.  Is there a better way to provide for this use case?

**Comment by jrgriffiniii** [comment]
After discussing this with @cjcolvar , it was determined that this was an extremely low priority, and could be closed until it is revisited for a future release.
