### ISSUE TITLE
roles generator messes up routes file

### ISSUE THREAD

**Issue by val99erie** [samvera/hydra-role-management#9]
I had this line in my routes file:

```
devise_for :users, controllers: { sessions: :sessions, registrations: :registrations}
```

When I ran "rails generate roles", it inserted the role management line in the middle of the devise line, so my routes file looked like this:

```
devise_for :users
mount Hydra::RoleManagement::Engine => '/'
, controllers: { sessions: :sessions, registrations: :registrations}
```

**Comment by cgalarza** [comment]
+1

Running the generators did the same thing for me.
